#pragma once

#include <QApplication>
#include <QDialog>
#include <QMainWindow>
#include <SceneViewer.hpp>
#include <memory>

class QListView;
class QStandardItemModel;

namespace Ui {
class App3DViewer;
}

/**
 * @brief Represents an object that is imported into the project and that can be loaded into the scene
 */
struct InfoObject
{
	QString name;		   ///< Display name of the object
	QString objectPath;	   ///< Path to the object's .obj file
	QString diffusePath;   ///< Path to the object's diffuse file
	QString specularPath;  ///< Path to the object's specular file
};

/**
 * @brief The view of the 3DApp, displaying the project's information
 */
class App3DViewer : public QMainWindow
{
	Q_OBJECT
   public:
	/**
	 * @brief Default constructor
	 * @param[in] scene 3D scene of the project
	 */
	explicit App3DViewer(Scene* scene);

	/**
	 * @brief Destructor
	 */
	~App3DViewer();

	/**
	 * @brief Set the model of the QListView displaying the object imported into the scene
	 * @param[in] sceneObjectModel The model
	 */
	void setSceneObjectsModel(QStandardItemModel* sceneObjectModel);

	/**
	 * @brief Initialize the OpenGL context, which is necessary to load the models of the project
	 */
	void initOGLContext(void);

	/**
	 * @brief Centers the application window on the main screen
	 */
	void centerScreen(void);

   signals:
	/**
	 * @brief Emits that a new model should be added to the project
	 * @param[in] info The information about the added object
	 */
	void newModelAdded(InfoObject info);

	/**
	 * @brief Emits that a new model should be loaded
	 * @param[in] modelIndex The index of the model to load
	 */
	void modelLoaded(uint modelIndex);

	/**
	 * @brief Indicates OpenGL has been initialized
	 */
	void initialized(void);

   private slots:

	/**
	 * @brief Opens up the explorer to imported new object onto the scene
	 * @param[in] checked The state of the button trigger the functino
     */
	void _openExplorer(bool checked);

	/**
	 * @brief Get what modelIndex should be loaded
	 * @param[in] checked The state of the button
	 */
	void _modelSelectedToLoad(bool checked);

   private:
	SceneViewer* m_sceneViewer;	   ///< The Qt OpenGL scene
	QListView* m_sceneObjectView;  ///< The list view representing the available objects in the project
	Ui::App3DViewer* ui;		   ///< The UI of the App3DViewer, generated by Qt
};