name: Windows-build
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      configure:
        required: true
        type: string
      build:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.3'
        host: windows
        target: desktop
        arch: win64_mingw
        tools: 'tools_mingw1310 tools_ninja'
        setup-python: 'false'

    - name: Check tools
      run: |
        g++ --version
        ninja --version
        cmake --version

    - name: Configure CMake
      run: >
        cmake --preset ${{ inputs.configure }}

    - name: Build
      run: cmake --build --preset ${{ inputs.build }}