name: windows-latest-mingw

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  windows-latest-build:
    uses: ./.github/workflows/windows-build.yml
    with:
      os: windows-latest
      configure: windows-mingw
      build: windows-mingw-b
      arch: win64_mingw
      tooling: tools_mingw1310