on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      configure:
        required: true
        type: string
      arch:
        required: true
        type: string
      tooling:
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.3'
        host: windows
        target: desktop
        arch: ${{ inputs.arch }}
        tools: 'tools_ninja ${{ inputs.tooling }}'
        setup-python: 'false'

    - name: Check tools
      run: |
        g++ --version
        ninja --version
        cmake --version

    - name: Configure CMake
      run: cmake --preset ${{ inputs.configure }}

    - name: Build
      run: cmake --build --preset ${{ inputs.configure }}

    - name: Run tests
      run: ctest --test-dir build/${{ inputs.configure }} -C Release --output-on-failure -VV